services:
  backend:
    build:
      context: ./backend
      target: development
    volumes:
      - ./backend:/var/www/html:cached
      - backend_vendor:/var/www/html/vendor
    ports:
      - "8000:8000"
    environment:
      - PHP_CLI_SERVER_WORKERS=4
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      db:
        condition: service_healthy
    networks:
      - local_network

  frontend:
    build:
      context: ./frontend
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:cached
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - local_network

  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - local_network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$MYSQL_ROOT_PASSWORD",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  db-viewer:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - local_network

networks:
  local_network:
    driver: bridge

volumes:
  db_data:
    name: laravel_db_data
  backend_vendor:
  frontend_node_modules:
